name: build-and-publish

on:
    push:
    workflow_dispatch:

env:
    REGISTRY: ghcr.io

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -   uses: actions/checkout@v4
            -   name: set lower case owner name
                run: |
                    echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >>${GITHUB_ENV}
                env:
                    IMAGE_NAME: '${{ github.repository }}'
            -   name: Build image
                run: docker build . --file Dockerfile --tag $IMAGE_NAME_LC --label "runnumber=${GITHUB_RUN_ID}"
            -   name: Log in to registry
                run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
            -   name: Push image
                run: |
                    IMAGE_ID=ghcr.io/$IMAGE_NAME_LC
                    IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
                    VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
                    [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
                    [ "$VERSION" == "main" ] && VERSION=latest
                    echo IMAGE_ID=$IMAGE_ID
                    echo VERSION=$VERSION
                    docker tag $IMAGE_NAME_LC $IMAGE_ID:$VERSION
                    docker push $IMAGE_ID:$VERSION